version: '2.4'
services:
  emscripten:
    build: .
    tty: true
    command: /bin/bash
    environment:
      EMSCRIPTEN: /emsdk/upstream/emscripten
      BUILD: debug
    working_dir: /app
    volumes:
      - ./:/app
